author:
        name: Microsoft

description: Use SQL Server ML Services to build and deploy a machine learning model which predicts whether a loan will charge off in the next three months.

gems:
  - jekyll-redirect-from

cig_text: SQL Server VM on Azure
onp_text: SQL Server On-Premises (with MicrosoftML)
hdi_text: HDInsight Spark 
db_name: LoanChargeOff_R
folder_name: LoanChargeOff

pbix_hdidownload_url: "https://github.com/Microsoft/r-server-loan-chargeoff/blob/master/HDI/LoanChargeOffPredictionDashboardHDI.pbix"
pbix_sqldownload_url: "https://github.com/Microsoft/r-server-loan-chargeoff/blob/master/SQLR/LoanChargeOffPredictionDashboardSQL.pbix"
pbix_hdiview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loanchargeoffhdi"
pbix_sqlview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loanchargeoffsql"
