author:
        name: Microsoft

description: Use SQL Server 2016 + R Services to build and deploy a machine learning model which predicts whether a loan will charge off in the next three months.

gems:
  - jekyll-redirect-from

cig_text: SQL Server 2016 on Azure
onp_text: SQL Server 2016 On-Prem 
hdi_text: HDInsight Spark 

pbix_hdidownload_url: "https://github.com/Microsoft/r-server-loan-chargeoff/blob/master/HDI/LoanChargeOffPredictionDashboardHDI.pbix"
pbix_sqldownload_url: "https://github.com/Microsoft/r-server-loan-chargeoff/blob/master/SQLR/LoanChargeOffPredictionDashboardSQL.pbix"
pbix_hdiview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loanchargeoffhdi"
pbix_sqlview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loanchargeoffsql"